cd "C:\mssql"
.\setup.exe /q /ACTION=Install /FEATURES=SQL /INSTANCENAME=MSSQLSERVER51 /SQLSVCACCOUNT="devops" /SQLSVCPASSWORD="Password@123" /SQLSYSADMINACCOUNTS="devops" /AGTSVCACCOUNT="NT AUTHORITY\Network Service" /UpdateEnabled=False /IACCEPTSQLSERVERLICENSETERMS
